image: monachus/hugo

variables:
  GIT_SUBMODULE_STRATEGY: recursive

pages:
  pre_clone_script:
  - apt-get install -y ssh-client
  script:
  - hugo
  artifacts:
    paths:
    - public
  only:
  - master
